### ISSUE TITLE
@dicebear/micah eyeColor seems to color the outer eye, but not the actual iris

### ISSUE THREAD

**Issue by WilliamRADFunk** [dicebear/dicebear#130] opened 2021-06-23 02:00 UTC
![image](https://user-images.githubusercontent.com/10148684/123022751-1b7ca300-d38b-11eb-9970-ecd7400c2912.png)

All avatars have the thick black iris+pupil regardless of provided eyeColors. It appears to only color what would be the white of a person's eyes.

Is this intentional?

When "eyes" prop is set to ['round'] or ['smiling'], it ignores eyeColor altogether:

![image](https://user-images.githubusercontent.com/10148684/123023015-86c67500-d38b-11eb-9d7b-b4160a23b8d2.png)

eyes: ['eyes'] has the same issue, but a little creepy, lol:

![image](https://user-images.githubusercontent.com/10148684/123023228-e6248500-d38b-11eb-9368-0bd528184145.png)

It's only with eyes: ['eyesShadow'] that the color appears. Is eyeColor really meant to mean "eyeShadowColor"?

**Comment by FlorianKoerner** [comment] 2021-06-23 04:21
I understand that behavior can be unexpected. However, it is actually the expected behavior. "eyeShadowColor" would really be a better name.

I think we should make both colors controllable. The problem is that this would be a breaking change, so it will have to wait for version 5.0.0.

**Comment by FlorianKoerner** [comment] 2021-06-23 06:23
`eyeColor` is now deprecated so it can be reassigned with version 5.0.0. Instead you can now use `eyeShadowColor`.

**Comment by WilliamRADFunk** [comment] 2021-06-23 19:25
Awesome. I completely understand about the breaking change concern. Again, thanks for the quick response. It's a great library.

**Comment by FlorianKoerner** [comment] 2021-09-13 15:24
Will be fixed with PR #153.

**Closed by FlorianKoerner** 2021-09-13 15:24 UTC
